export const Category = {
  // Expense
  HOUSING: "HOUSING",
  FOOD: "FOOD",
  TRANSPORTATION: "TRANSPORTATION",
  UTILITIES: "UTILITIES",
  ENTERTAINMENT: "ENTERTAINMENT",
  HEALTH: "HEALTH",
  EDUCATION: "EDUCATION",
  SHOPPING: "SHOPPING",
  SUBSCRIPTIONS: "SUBSCRIPTIONS",
  PERSONAL: "PERSONAL",
  TRAVEL: "TRAVEL",
  MISC: "MISC",

  // Income
  SALARY: "SALARY",
  BUSINESS: "BUSINESS",
  FREELANCE: "FREELANCE",
  INVESTMENT: "INVESTMENT",
  BONUS: "BONUS",
  GIFT: "GIFT",
  OTHER_INCOME: "OTHER_INCOME",
} as const;

export type Category = (typeof Category)[keyof typeof Category];
